version: '3'

services:

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    restart: always

  api:
    image: app
    build:
      context: src
    container_name: api
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - docker.env

  rate:
    image: rate
    build:
      context: ./rate-service
    container_name: rate
    ports:
      - "8080:8080"
    restart: always

  mail:
    image: mail
    build:
      context: ./mail-service
    container_name: mail
    ports:
      - "8082:8082"
    restart: always