version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - backend
    ports:
      - "6379:6379"
    restart: always

  postgres:
    image: postgres:latest
    networks:
      - backend
    ports:
      - "5432:5432"
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: marketplace
    restart: always

  api:
    image: api
    build:
      context: src
      dockerfile: Dockerfile
    networks:
      - backend
    container_name: api
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - "8081:8081"
    env_file:
      - docker.env

  rate:
    image: rate
    networks:
      - backend
    build:
      context: ./rate-service
      dockerfile: Dockerfile
    container_name: rate
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    restart: always

  mail:
    image: mail
    networks:
      - backend
    depends_on:
      - postgres
    build:
      context: ./mail-service
      dockerfile: Dockerfile
    container_name: mail
    ports:
      - "8082:8082"
    restart: always
    env_file:
      - ./mail-service/docker.env

networks:
  backend:
    driver: bridge