spring.application.name: marketplace

spring.datasource:
  password: ILin47gim
  username: postgres
  url: jdbc:postgresql://localhost:5432/marketplace
  driver-class-name: org.postgresql.Driver

app:
    scheduling:
      period: 30000
      enabled: true
    file:
      path: C:\\marketplace\\marketplace\\src\\main\\resources\\reports\\
    download-upload:
      path: C:\\marketplace\\marketplace\\src\\main\\resources\\files\\

server.port: 8081


