spring.application.name: marketplace

spring:
  datasource:
     password: ILin47gim
     username: postgres
     url: jdbc:postgresql://localhost:5432/marketplace
     driver-class-name: org.postgresql.Driver
  redis:
    host: localhost
    port: 6378
    time-to-live: 10

app:
  default:
    rate-value: 1
  scheduling:
    period: 30000
    enabled: true
  file:
    path: C:\\marketplace\\marketplace\\src\\main\\resources\\reports\\
  download-upload:
    path: C:\\marketplace\\marketplace\\src\\main\\resources\\files\\
  json:
    path: C:\marketplace\marketplace\src\main\resources\json\\dollar_exchange_rate.json
  feign-client:
    url: http://localhost:8080/

server.port: 8081

