spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  cloud:
    config:
      enabled: false
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  server:
    url: http://localhost:${server.port}
  default:
    rate-value: 1
  scheduling:
    period: 30000
    enabled: false
  file:
    path: C:\\marketplace\\marketplace\\src\\main\\resources\\reports\\
  download-upload:
    path: C:\\marketplace\\marketplace\\src\\main\\resources\\files\\
  json:
    path: C:\marketplace\marketplace\src\main\resources\json\\dollar_exchange_rate.json
  feign-client:
    rate-service:
      url: http://localhost:8080/
    mail-service:
      url: http://localhost:8085/

server:
  port: 8081

management:
  zipkin:
    tracing:
      export:
        enabled: false