spring.application.name: marketplace

spring.datasource:
  password: ILin47gim
  username: postgres
  url: jdbc:postgresql://localhost:5432/marketplace
  driver-class-name: org.postgresql.Driver

app:
    scheduling:
      period: 30000
      enabled: true

server.port: 8081


