spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver

app:
  scheduling:
    period: 30000
    enabled: true

server:
  port: 8081
