spring.application.name: marketplace

spring:
  datasource:
     password: ILin47gim
     username: postgres
     url: jdbc:postgresql://localhost:5432/marketplace
     driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  redis:
    host: localhost
    port: 6378
    time-to-live: 10

app:
  default:
    rate-value: 1
  scheduling:
    period: 30000
    enabled: false
  file:
    path: C:\\marketplace\\marketplace\\src\\main\\resources\\reports\\
  download-upload:
    path: C:\\marketplace\\marketplace\\src\\main\\resources\\files\\
  json:
    path: C:\marketplace\marketplace\src\main\resources\json\\dollar_exchange_rate.json
  feign-client:
    rate-service:
         url: http://localhost:8080/
    mail-service:
         url: http://localhost:8085/

server.port: 8081

