spring.application:
  name: rate-service

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}