spring:
  application:
    name: rate-service
  cloud:
    config:
      enabled: false

server:
  port: 8080

eureka:
  client:
    enabled: false

management:
  zipkin:
    tracing:
      export:
        enabled: false