spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: git@github.com:VadimShepelin/marketplace.git
          default-label: develop
          search-paths: config/cloud/{application}
server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
