name: Marketplace CI/CD Pipeline

# Build stages
# -Build
# -Test
# -Deploy

on:
  push:
    branches: ["develop","feature/task25"]
  pull_request:
    branches: ["develop"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repository
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install -DskipTests
      - name: Build image of Markeplace api
        run: docker build -f Dockerfile -t marketplace:latest .
  deploy:
    runs-on: self-hosted
    needs: build-test
    steps:
      - name: Deploy Marketplace Api
        uses: actions/checkout@v3
      - name: Run Docker container
        run: docker-compose up -d

