name: Marketplace CI/CD Pipeline

# Build stages
# -Build
# -Test
# -Deploy

on:
  push:
    branches: ["develop","feature/task25"]
  pull_request:
    branches: ["develop"]

jobs:
  build-test:
    runs-on: self-hosted
    steps:
      - name: Get code from repository
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2
      - name: Run Maven Marketplace Api
        run: mvn clean package -DskipTests
      - name: Build image of Markeplace api
        run: docker build -f Dockerfile -t app:latest .
      - name: Go to the rate directory
        run: cd rate-service
      - name: Run maven rate api
        run: mvn clean package -DskipTests
      - name: Build image of rate Api
        run: docker build -f Dockerfile -t rate:latest .
  deploy:
    runs-on: self-hosted
    needs: build-test
    steps:
      - name: Deploy Marketplace Api
        uses: actions/checkout@v3
      - name: Cleanup container
        uses: kacus/github-action-container-cleanup@v1.0.0
      - name: Run Docker container
        run: docker-compose up -d

