name: Marketplace CI/CD Pipeline

# Build stages
# -Build
# -Test
# -Deploy

on:
  push:
    branches: ["develop","feature/task25"]
  pull_request:
    branches: ["develop"]

jobs:
  build-test:
    runs-on: self-hosted
    steps:
      - name: Get code from repository
        uses: actions/checkout@v3
      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2
      - name: Run Maven Marketplace Api
        run: mvn clean package -DskipTests
      - name: Build image of markeplace api
        run: docker build -f Dockerfile -t api:latest .
      - name: Run maven rate api
        run: cd rate-service && mvn clean package -DskipTests
      - name: Build image of rate api
        run: docker build -f ./rate-service/Dockerfile -t rate:latest ./rate-service
      - name: Run maven mail api
        run: cd mail-service && mvn clean package -DskipTests
      - name: Build mail image
        run: docker build -f ./mail-service/Dockerfile -t mail:latest ./mail-service
  deploy:
    runs-on: self-hosted
    needs: build-test
    steps:
      - name: Run docker container
        run: docker-compose up -d
      - name: Docker images prune
        run: docker image prune -a

